#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  7 23:48:16 2018

@author: sulbha
"""

# s= 'ab[ab]cd' == abbacd
def addBorder(picture):
    l = len(picture) 
    
    f= [x.center(l+2,'*') for x in picture]
    print(f)
